// spec: specs/plan.md
// seed: e2e/seed.spec.ts

import { test, expect } from '@playwright/test';

test.describe('Page Metadata & Branding', () => {
  test('Page loads with correct title and description', async ({ page }) => {
    // 1. Navigate to /
    await page.goto('http://localhost:3000/');

    // 2. Read the document title
    await expect(page).toHaveTitle(/Create Next App/);

    // 3. Read the <meta name="description"> content
    await expect(page.locator('meta[name="description"]')).toHaveAttribute(
      'content',
      'Generated by create next app',
    );
  });
});
